; automatically generated by FrederoxDev/Header-Test
section .text

extern Dimension_vtable
extern Dimension_for_LevelListener_vtable
extern Dimension_for_SavedData_vtable
extern Dimension_ctor

global ??_DDimension@@QEAAXXZ
??_DDimension@@QEAAXXZ:
	mov rax, [rel Dimension_vtable]
	xor edx, edx
	jmp [rax + 0]

global ?isNaturalDimension@Dimension@@UEBA_NXZ
?isNaturalDimension@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 8]

global ?getDimensionId@Dimension@@UEBA?AV?$AutomaticID@VDimension@@H@@XZ
?getDimensionId@Dimension@@UEBA?AV?$AutomaticID@VDimension@@H@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 16]

global ?sendPacketForPosition@Dimension@@UEAAXAEBVBlockPos@@AEBVPacket@@PEBVPlayer@@@Z
?sendPacketForPosition@Dimension@@UEAAXAEBVBlockPos@@AEBVPacket@@PEBVPlayer@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 24]

global ?flushLevelChunkGarbageCollector@Dimension@@UEAAXXZ
?flushLevelChunkGarbageCollector@Dimension@@UEAAXXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 32]

global ?initializeWithLevelStorageManager@Dimension@@UEAAXAEAVLevelStorageManager@@@Z
?initializeWithLevelStorageManager@Dimension@@UEAAXAEAVLevelStorageManager@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 40]

global ?getBiomeRegistry@Dimension@@UEAAAEAVBiomeRegistry@@XZ
?getBiomeRegistry@Dimension@@UEAAAEAVBiomeRegistry@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 48]

global ?getBiomeRegistry@Dimension@@UEBAAEBVBiomeRegistry@@XZ
?getBiomeRegistry@Dimension@@UEBAAEBVBiomeRegistry@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 56]

global ?translatePosAcrossDimension@Dimension@@UEBA?AVVec3@@AEBV2@V?$AutomaticID@VDimension@@H@@@Z
?translatePosAcrossDimension@Dimension@@UEBA?AVVec3@@AEBV2@V?$AutomaticID@VDimension@@H@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 64]

global ?forEachPlayer@Dimension@@UEBAXV?$function@$$A6A_NAEAVPlayer@@@Z@std@@@Z
?forEachPlayer@Dimension@@UEBAXV?$function@$$A6A_NAEAVPlayer@@@Z@std@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 72]

global ?fetchEntity@Dimension@@UEBAPEAVActor@@UActorUniqueID@@_N@Z
?fetchEntity@Dimension@@UEBAPEAVActor@@UActorUniqueID@@_N@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 80]

global ?init@Dimension@@UEAAXAEBUStructureSetRegistry@worldgen@br@@@Z
?init@Dimension@@UEAAXAEBUStructureSetRegistry@worldgen@br@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 88]

global ?tick@Dimension@@UEAAXXZ
?tick@Dimension@@UEAAXXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 96]

global ?tickRedstone@Dimension@@UEAAXXZ
?tickRedstone@Dimension@@UEAAXXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 104]

global ?createGenerator@Dimension@@UEAA?AV?$unique_ptr@VWorldGenerator@@U?$default_delete@VWorldGenerator@@@std@@@std@@AEBUStructureSetRegistry@worldgen@br@@@Z
?createGenerator@Dimension@@UEAA?AV?$unique_ptr@VWorldGenerator@@U?$default_delete@VWorldGenerator@@@std@@@std@@AEBUStructureSetRegistry@worldgen@br@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 112]

global ?upgradeLevelChunk@Dimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@1@Z
?upgradeLevelChunk@Dimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@1@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 120]

global ?fixWallChunk@Dimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@@Z
?fixWallChunk@Dimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 128]

global ?levelChunkNeedsUpgrade@Dimension@@UEBA_NAEBVLevelChunk@@@Z
?levelChunkNeedsUpgrade@Dimension@@UEBA_NAEBVLevelChunk@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 136]

global ?isValidSpawn@Dimension@@UEBA_NHH@Z
?isValidSpawn@Dimension@@UEBA_NHH@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 144]

global ?getBrightnessDependentFogColor@Dimension@@UEBA?AVColor@mce@@AEBV23@M@Z
?getBrightnessDependentFogColor@Dimension@@UEBA?AVColor@mce@@AEBV23@M@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 152]

global ?hasPrecipitationFog@Dimension@@UEBA_NXZ
?hasPrecipitationFog@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 160]

global ?getCloudHeight@Dimension@@UEBAFXZ
?getCloudHeight@Dimension@@UEBAFXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 168]

global ?getDefaultBiome@Dimension@@UEBA?AVHashedString@@XZ
?getDefaultBiome@Dimension@@UEBA?AVHashedString@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 176]

global ?hasGround@Dimension@@UEBA_NXZ
?hasGround@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 184]

global ?showSky@Dimension@@UEBA_NXZ
?showSky@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 192]

global ?getSpawnPos@Dimension@@UEBA?AVBlockPos@@XZ
?getSpawnPos@Dimension@@UEBA?AVBlockPos@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 200]

global ?getSpawnYPosition@Dimension@@UEBAHXZ
?getSpawnYPosition@Dimension@@UEBAHXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 208]

global ?mayRespawnViaBed@Dimension@@UEBA_NXZ
?mayRespawnViaBed@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 216]

global ?isDay@Dimension@@UEBA_NXZ
?isDay@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 224]

global ?getTimeOfDay@Dimension@@UEBAMHM@Z
?getTimeOfDay@Dimension@@UEBAMHM@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 232]

global ?getSunIntensity@Dimension@@UEBAMMAEBVVec3@@M@Z
?getSunIntensity@Dimension@@UEBAMMAEBVVec3@@M@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 240]

global ?forceCheckAllNeighChunkSavedStat@Dimension@@UEBA_NXZ
?forceCheckAllNeighChunkSavedStat@Dimension@@UEBA_NXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 248]

global ?sendBroadcast@Dimension@@UEAAXAEBVPacket@@PEAVPlayer@@@Z
?sendBroadcast@Dimension@@UEAAXAEBVPacket@@PEAVPlayer@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 256]

global ?is2DPositionRelevantForPlayer@Dimension@@UEBA_NAEBVBlockPos@@AEAVPlayer@@@Z
?is2DPositionRelevantForPlayer@Dimension@@UEBA_NAEBVBlockPos@@AEAVPlayer@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 264]

global ?isActorRelevantForPlayer@Dimension@@UEBA_NAEAVPlayer@@AEBVActor@@@Z
?isActorRelevantForPlayer@Dimension@@UEBA_NAEAVPlayer@@AEBVActor@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 272]

global ?getLightTextureImageBuilder@Dimension@@UEBAPEAVBaseLightTextureImageBuilder@@XZ
?getLightTextureImageBuilder@Dimension@@UEBAPEAVBaseLightTextureImageBuilder@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 280]

global ?getBrightnessRamp@Dimension@@UEBAAEBVDimensionBrightnessRamp@@XZ
?getBrightnessRamp@Dimension@@UEBAAEBVDimensionBrightnessRamp@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 288]

global ?startLeaveGame@Dimension@@UEAAXXZ
?startLeaveGame@Dimension@@UEAAXXZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 296]

global ?_createChunkBuildOrderPolicy@Dimension@@UEAA?AV?$unique_ptr@VChunkBuildOrderPolicyBase@@U?$default_delete@VChunkBuildOrderPolicyBase@@@std@@@std@@XZ
?_createChunkBuildOrderPolicy@Dimension@@UEAA?AV?$unique_ptr@VChunkBuildOrderPolicyBase@@U?$default_delete@VChunkBuildOrderPolicyBase@@@std@@@std@@XZ:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 304]

global ?_upgradeOldLimboEntity@Dimension@@UEAAXAEAVCompoundTag@@W4LimboEntitiesVersion@@@Z
?_upgradeOldLimboEntity@Dimension@@UEAAXAEAVCompoundTag@@W4LimboEntitiesVersion@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 312]

global ?_wrapStorageForVersionCompatibility@Dimension@@UEAA?AV?$unique_ptr@VChunkSource@@U?$default_delete@VChunkSource@@@std@@@std@@V23@W4StorageVersion@@@Z
?_wrapStorageForVersionCompatibility@Dimension@@UEAA?AV?$unique_ptr@VChunkSource@@U?$default_delete@VChunkSource@@@std@@@std@@V23@W4StorageVersion@@@Z:
	mov rax, [rel Dimension_vtable]
	jmp [rax + 320]

global ?deserialize@Dimension@@UEAAXAEBVCompoundTag@@@Z
?deserialize@Dimension@@UEAAXAEBVCompoundTag@@@Z:
	mov rax, [rel Dimension_for_SavedData_vtable]
	jmp [rax + 8]

global ?serialize@Dimension@@UEBAXAEAVCompoundTag@@@Z
?serialize@Dimension@@UEBAXAEAVCompoundTag@@@Z:
	mov rax, [rel Dimension_for_SavedData_vtable]
	jmp [rax + 16]

global ?onBlockChanged@Dimension@@UEAAXAEAVBlockSource@@AEBVBlockPos@@IAEBVBlock@@2HPEBUActorBlockSyncMessage@@W4BlockChangedEventTarget@@PEAVActor@@@Z
?onBlockChanged@Dimension@@UEAAXAEAVBlockSource@@AEBVBlockPos@@IAEBVBlock@@2HPEBUActorBlockSyncMessage@@W4BlockChangedEventTarget@@PEAVActor@@@Z:
	mov rax, [rel Dimension_for_LevelListener_vtable]
	jmp [rax + 32]

global ?onBrightnessChanged@Dimension@@UEAAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onBrightnessChanged@Dimension@@UEAAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel Dimension_for_LevelListener_vtable]
	jmp [rax + 40]

global ?onBlockEvent@Dimension@@UEAAXAEAVBlockSource@@HHHHH@Z
?onBlockEvent@Dimension@@UEAAXAEAVBlockSource@@HHHHH@Z:
	mov rax, [rel Dimension_for_LevelListener_vtable]
	jmp [rax + 64]

global ?onChunkLoaded@Dimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@@Z
?onChunkLoaded@Dimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@@Z:
	mov rax, [rel Dimension_for_LevelListener_vtable]
	jmp [rax + 152]

global ?onLevelDestruction@Dimension@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
?onLevelDestruction@Dimension@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov rax, [rel Dimension_for_LevelListener_vtable]
	jmp [rax + 184]

global ??0Dimension@@QEAA@AEAVILevel@@V?$AutomaticID@VDimension@@H@@VDimensionHeightRange@@AEAVScheduler@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
??0Dimension@@QEAA@AEAVILevel@@V?$AutomaticID@VDimension@@H@@VDimensionHeightRange@@AEAVScheduler@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov rax, [rel Dimension_ctor]
	jmp rax