; automatically generated by FrederoxDev/Header-Test
section .text

extern StructureFeatureRegistry_vtable
extern StructureFeatureRegistry_ctor

global ??0StructureFeatureRegistry@@QEAA@XZ
??0StructureFeatureRegistry@@QEAA@XZ:
	mov rax, [rel StructureFeatureRegistry_ctor]
	jmp rax