; automatically generated by FrederoxDev/Header-Test
section .text

extern ChunkSource_vtable

global ??1ChunkSource@@UEAA@XZ
??1ChunkSource@@UEAA@XZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 0]

global ?shutdown@ChunkSource@@UEAAXXZ
?shutdown@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 8]

global ?isShutdownDone@ChunkSource@@UEAA_NXZ
?isShutdownDone@ChunkSource@@UEAA_NXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 16]

global ?getExistingChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEBVChunkPos@@@Z
?getExistingChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEBVChunkPos@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 24]

global ?getRandomChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEAVRandom@@@Z
?getRandomChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEAVRandom@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 32]

global ?isChunkKnown@ChunkSource@@UEAA_NAEBVChunkPos@@@Z
?isChunkKnown@ChunkSource@@UEAA_NAEBVChunkPos@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 40]

global ?isChunkSaved@ChunkSource@@UEAA_NAEBVChunkPos@@@Z
?isChunkSaved@ChunkSource@@UEAA_NAEBVChunkPos@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 48]

global ?createNewChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEBVChunkPos@@W4LoadMode@1@_N@Z
?createNewChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEBVChunkPos@@W4LoadMode@1@_N@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 56]

global ?getOrLoadChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEBVChunkPos@@W4LoadMode@1@_N@Z
?getOrLoadChunk@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunk@@@std@@AEBVChunkPos@@W4LoadMode@1@_N@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 64]

global ?postProcess@ChunkSource@@UEAA_NAEAVChunkViewSource@@@Z
?postProcess@ChunkSource@@UEAA_NAEAVChunkViewSource@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 72]

global ?checkAndReplaceChunk@ChunkSource@@UEAAXAEAVChunkViewSource@@AEAVLevelChunk@@@Z
?checkAndReplaceChunk@ChunkSource@@UEAAXAEAVChunkViewSource@@AEAVLevelChunk@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 80]

global ?loadChunk@ChunkSource@@UEAAXAEAVLevelChunk@@_N@Z
?loadChunk@ChunkSource@@UEAAXAEAVLevelChunk@@_N@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 88]

global ?postProcessMobsAt@ChunkSource@@UEAAXAEAVBlockSource@@HHAEAVRandom@@@Z
?postProcessMobsAt@ChunkSource@@UEAAXAEAVBlockSource@@HHAEAVRandom@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 96]

global ?saveLiveChunk@ChunkSource@@UEAA_NAEAVLevelChunk@@@Z
?saveLiveChunk@ChunkSource@@UEAA_NAEAVLevelChunk@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 104]

global ?writeEntityChunkTransfer@ChunkSource@@UEAAXAEAVLevelChunk@@@Z
?writeEntityChunkTransfer@ChunkSource@@UEAAXAEAVLevelChunk@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 112]

global ?writeEntityChunkTransfersToUnloadedChunk@ChunkSource@@UEAAXAEBVChunkKey@@AEBV?$vector@UActorUnloadedChunkTransferEntry@@V?$allocator@UActorUnloadedChunkTransferEntry@@@std@@@std@@@Z
?writeEntityChunkTransfersToUnloadedChunk@ChunkSource@@UEAAXAEBVChunkKey@@AEBV?$vector@UActorUnloadedChunkTransferEntry@@V?$allocator@UActorUnloadedChunkTransferEntry@@@std@@@std@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 120]

global ?deserializeActorStorageToLevelChunk@ChunkSource@@UEAAXAEAVLevelChunk@@@Z
?deserializeActorStorageToLevelChunk@ChunkSource@@UEAAXAEAVLevelChunk@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 128]

global ?hintDiscardBatchBegin@ChunkSource@@UEAAXXZ
?hintDiscardBatchBegin@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 136]

global ?hintDiscardBatchEnd@ChunkSource@@UEAAXXZ
?hintDiscardBatchEnd@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 144]

global ?acquireDiscarded@ChunkSource@@UEAAXV?$unique_ptr@VLevelChunk@@ULevelChunkFinalDeleter@@@std@@@Z
?acquireDiscarded@ChunkSource@@UEAAXV?$unique_ptr@VLevelChunk@@ULevelChunkFinalDeleter@@@std@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 152]

global ?compact@ChunkSource@@UEAAXXZ
?compact@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 160]

global ?flushPendingDiscardedChunkWrites@ChunkSource@@UEAAXXZ
?flushPendingDiscardedChunkWrites@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 168]

global ?flushThreadBatch@ChunkSource@@UEAAXXZ
?flushThreadBatch@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 176]

global ?isWithinWorldLimit@ChunkSource@@UEBA_NAEBVChunkPos@@@Z
?isWithinWorldLimit@ChunkSource@@UEBA_NAEBVChunkPos@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 184]

global ?getChunkMap@ChunkSource@@UEAAPEBV?$unordered_map@VChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@U?$hash@VChunkPos@@@3@U?$equal_to@VChunkPos@@@3@V?$allocator@U?$pair@$$CBVChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@@std@@@3@@std@@XZ
?getChunkMap@ChunkSource@@UEAAPEBV?$unordered_map@VChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@U?$hash@VChunkPos@@@3@U?$equal_to@VChunkPos@@@3@V?$allocator@U?$pair@$$CBVChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@@std@@@3@@std@@XZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 192]

global ?getStorage@ChunkSource@@UEBAAEBV?$unordered_map@VChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@U?$hash@VChunkPos@@@3@U?$equal_to@VChunkPos@@@3@V?$allocator@U?$pair@$$CBVChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@@std@@@3@@std@@XZ
?getStorage@ChunkSource@@UEBAAEBV?$unordered_map@VChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@U?$hash@VChunkPos@@@3@U?$equal_to@VChunkPos@@@3@V?$allocator@U?$pair@$$CBVChunkPos@@V?$weak_ptr@VLevelChunk@@@std@@@std@@@3@@std@@XZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 200]

global ?clearDeletedEntities@ChunkSource@@UEAAXXZ
?clearDeletedEntities@ChunkSource@@UEAAXXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 208]

global ?canCreateViews@ChunkSource@@UEBA_NXZ
?canCreateViews@ChunkSource@@UEBA_NXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 216]

global ?tryGetBlendingDataProvider@ChunkSource@@UEAA?AV?$unique_ptr@VBlendingDataProvider@@U?$default_delete@VBlendingDataProvider@@@std@@@std@@XZ
?tryGetBlendingDataProvider@ChunkSource@@UEAA?AV?$unique_ptr@VBlendingDataProvider@@U?$default_delete@VBlendingDataProvider@@@std@@@std@@XZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 224]

global ?loadLevelChunkMetaDataDictionary@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunkMetaDataDictionary@@@std@@XZ
?loadLevelChunkMetaDataDictionary@ChunkSource@@UEAA?AV?$shared_ptr@VLevelChunkMetaDataDictionary@@@std@@XZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 232]

global ?setLevelChunk@ChunkSource@@UEAAXV?$shared_ptr@VLevelChunk@@@std@@@Z
?setLevelChunk@ChunkSource@@UEAAXV?$shared_ptr@VLevelChunk@@@std@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 240]

global ?canLaunchTasks@ChunkSource@@UEBA_NXZ
?canLaunchTasks@ChunkSource@@UEBA_NXZ:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 248]

global ?chunkPosNeedsBlending@ChunkSource@@UEAA_NAEBVChunkPos@@@Z
?chunkPosNeedsBlending@ChunkSource@@UEAA_NAEBVChunkPos@@@Z:
	mov rax, [rel ChunkSource_vtable]
	jmp [rax + 256]



