; Automatically generated assembly for virtual function definitions
; generated by FrederoxDev/Virtual-Headers
section .text
extern BlockActor_vtable
extern BlockActor_ctor

global ??0BlockActor@@QEAA@W4BlockActorType@@AEBVBlockPos@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
??0BlockActor@@QEAA@W4BlockActorType@@AEBVBlockPos@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
    mov rax, [rel BlockActor_ctor]
    jmp rax

global ??1BlockActor@@UEAA@XZ
??1BlockActor@@UEAA@XZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 0]

global ?load@BlockActor@@UEAAXAEAVLevel@@AEBVCompoundTag@@AEAVDataLoadHelper@@@Z
?load@BlockActor@@UEAAXAEAVLevel@@AEBVCompoundTag@@AEAVDataLoadHelper@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 8]

global ?save@BlockActor@@UEBA_NAEAVCompoundTag@@@Z
?save@BlockActor@@UEBA_NAEAVCompoundTag@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 16]

global ?saveItemInstanceData@BlockActor@@UEBA_NAEAVCompoundTag@@@Z
?saveItemInstanceData@BlockActor@@UEBA_NAEAVCompoundTag@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 24]

global ?setUgcStrings@BlockActor@@UEBAXAEAVCompoundTag@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z
?setUgcStrings@BlockActor@@UEBAXAEAVCompoundTag@@AEBV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 32]

global ?loadBlockData@BlockActor@@UEAAXAEBVCompoundTag@@AEAVBlockSource@@AEAVDataLoadHelper@@@Z
?loadBlockData@BlockActor@@UEAAXAEBVCompoundTag@@AEAVBlockSource@@AEAVDataLoadHelper@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 40]

global ?onCustomTagLoadDone@BlockActor@@UEAAXAEAVBlockSource@@@Z
?onCustomTagLoadDone@BlockActor@@UEAAXAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 48]

global ?tick@BlockActor@@UEAAXAEAVBlockSource@@@Z
?tick@BlockActor@@UEAAXAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 56]

global ?onChanged@BlockActor@@UEAAXAEAVBlockSource@@@Z
?onChanged@BlockActor@@UEAAXAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 64]

global ?isMovable@BlockActor@@UEAA_NAEAVBlockSource@@@Z
?isMovable@BlockActor@@UEAA_NAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 72]

global ?isCustomNameSaved@BlockActor@@UEAA_NXZ
?isCustomNameSaved@BlockActor@@UEAA_NXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 80]

global ?onPlace@BlockActor@@UEAAXAEAVBlockSource@@@Z
?onPlace@BlockActor@@UEAAXAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 88]

global ?onMove@BlockActor@@UEAAXXZ
?onMove@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 96]

global ?onRemoved@BlockActor@@UEAAXAEAVBlockSource@@@Z
?onRemoved@BlockActor@@UEAAXAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 104]

global ?isPreserved@BlockActor@@UEBA_NAEAVBlockSource@@@Z
?isPreserved@BlockActor@@UEBA_NAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 112]

global ?shouldPreserve@BlockActor@@UEAA_NAEAVBlockSource@@@Z
?shouldPreserve@BlockActor@@UEAA_NAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 120]

global ?triggerEvent@BlockActor@@UEBAXHH@Z
?triggerEvent@BlockActor@@UEBAXHH@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 128]

global ?clearCache@BlockActor@@UEAAXXZ
?clearCache@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 136]

global ?onNeighborChanged@BlockActor@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onNeighborChanged@BlockActor@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 144]

global ?getShadowRadius@BlockActor@@UEBAMAEAVBlockSource@@@Z
?getShadowRadius@BlockActor@@UEBAMAEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 152]

global ?hasAlphaLayer@BlockActor@@UEBA_NXZ
?hasAlphaLayer@BlockActor@@UEBA_NXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 160]

global ?getCrackEntity@BlockActor@@UEAAPEAV1@AEAVBlockSource@@AEBVBlockPos@@@Z
?getCrackEntity@BlockActor@@UEAAPEAV1@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 168]

global ?getCollisionShape@BlockActor@@UEBA?AVAABB@@AEBVIConstBlockSource@@@Z
?getCollisionShape@BlockActor@@UEBA?AVAABB@@AEBVIConstBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 176]

global ?getDebugText@BlockActor@@UEAAXAEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVBlockPos@@@Z
?getDebugText@BlockActor@@UEAAXAEAV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 184]

global ?getCustomName@BlockActor@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
?getCustomName@BlockActor@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 192]

global ?getFilteredCustomName@BlockActor@@UEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$not_null@V?$NonOwnerPointer@VUIProfanityContext@@@Bedrock@@@gsl@@@Z
?getFilteredCustomName@BlockActor@@UEAAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$not_null@V?$NonOwnerPointer@VUIProfanityContext@@@Bedrock@@@gsl@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 200]

global ?getName@BlockActor@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
?getName@BlockActor@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 208]

global ?setCustomName@BlockActor@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
?setCustomName@BlockActor@@UEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 216]

global ?getImmersiveReaderText@BlockActor@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVBlockSource@@@Z
?getImmersiveReaderText@BlockActor@@UEAA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 224]

global ?getRepairCost@BlockActor@@UEBAHXZ
?getRepairCost@BlockActor@@UEBAHXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 232]

; BlockActor_vtable[30] is unknown
global ?_unknown_30@BlockActor@@UEAAXXZ
?_unknown_30@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 240]

; BlockActor_vtable[31] is unknown
global ?_unknown_31@BlockActor@@UEAAXXZ
?_unknown_31@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 248]

; BlockActor_vtable[32] is unknown
global ?_unknown_32@BlockActor@@UEAAXXZ
?_unknown_32@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 256]

; BlockActor_vtable[33] is unknown
global ?_unknown_33@BlockActor@@UEAAXXZ
?_unknown_33@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 264]

global ?eraseLootTable@BlockActor@@UEAAXXZ
?eraseLootTable@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 272]

; BlockActor_vtable[35] is unknown
global ?_unknown_35@BlockActor@@UEAAXXZ
?_unknown_35@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 280]

; BlockActor_vtable[36] is unknown
global ?_unknown_36@BlockActor@@UEAAXXZ
?_unknown_36@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 288]

global ?getUgcStrings@BlockActor@@UEBA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVCompoundTag@@@Z
?getUgcStrings@BlockActor@@UEBA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVCompoundTag@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 296]

; BlockActor_vtable[38] is unknown
global ?_unknown_38@BlockActor@@UEAAXXZ
?_unknown_38@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 304]

; BlockActor_vtable[39] is unknown
global ?_unknown_39@BlockActor@@UEAAXXZ
?_unknown_39@BlockActor@@UEAAXXZ:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 312]

global ?_getUpdatePacket@BlockActor@@MEAA?AV?$unique_ptr@VBlockActorDataPacket@@U?$default_delete@VBlockActorDataPacket@@@std@@@std@@AEAVBlockSource@@@Z
?_getUpdatePacket@BlockActor@@MEAA?AV?$unique_ptr@VBlockActorDataPacket@@U?$default_delete@VBlockActorDataPacket@@@std@@@std@@AEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 320]

global ?_onUpdatePacket@BlockActor@@MEAAXAEBVCompoundTag@@AEAVBlockSource@@@Z
?_onUpdatePacket@BlockActor@@MEAAXAEBVCompoundTag@@AEAVBlockSource@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 328]

global ?_playerCanUpdate@BlockActor@@MEBA_NAEBVPlayer@@@Z
?_playerCanUpdate@BlockActor@@MEBA_NAEBVPlayer@@@Z:
	mov rax, [rel BlockActor_vtable]
	jmp [rax + 336]