; Automatically generated assembly for virtual function definitions
; generated by FrederoxDev/Virtual-Headers
section .text
extern BlockLegacy_vtable
extern BlockLegacy_ctor

global ??0BlockLegacy@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@FAEBVMaterial@@@Z
??0BlockLegacy@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@FAEBVMaterial@@@Z:
    mov rax, [rel BlockLegacy_ctor]
    jmp rax

global ??_EBlockLegacy@@UEAAPEAXI@Z
??_EBlockLegacy@@UEAAPEAXI@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 0]

global ?newBlockEntity@BlockLegacy@@UEBA?AV?$shared_ptr@VBlockActor@@@std@@AEBVBlockPos@@AEBVBlock@@@Z
?newBlockEntity@BlockLegacy@@UEBA?AV?$shared_ptr@VBlockActor@@@std@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 8]

global ?getNextBlockPermutation@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
?getNextBlockPermutation@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 16]

global ?waterSpreadCausesSpawn@BlockLegacy@@UEBA_NXZ
?waterSpreadCausesSpawn@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 24]

global ?clip@BlockLegacy@@UEBA?AVHitResult@@AEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@AEBVVec3@@3W4ShapeType@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
?clip@BlockLegacy@@UEBA?AVHitResult@@AEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@AEBVVec3@@3W4ShapeType@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 32]

global ?getCollisionShape@BlockLegacy@@UEBA?AVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
?getCollisionShape@BlockLegacy@@UEBA?AVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 40]

global ?getCollisionShapeForCamera@BlockLegacy@@UEBA_NAEAVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@@Z
?getCollisionShapeForCamera@BlockLegacy@@UEBA_NAEAVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 48]

global ?addCollisionShapes@BlockLegacy@@UEBA_NAEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
?addCollisionShapes@BlockLegacy@@UEBA_NAEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 56]

global ?addAABBs@BlockLegacy@@UEBAXAEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@@Z
?addAABBs@BlockLegacy@@UEBAXAEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 64]

global ?getOutline@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z
?getOutline@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 72]

global ?getVisualShapeInWorld@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z
?getVisualShapeInWorld@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 80]

global ?getVisualShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z
?getVisualShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 88]

global ?getUIShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z
?getUIShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 96]

global ?getLiquidClipVolume@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEAVAABB@@@Z
?getLiquidClipVolume@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEAVAABB@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 104]

global ?isObstructingChests@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?isObstructingChests@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 112]

global ?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@@Z
?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 120]

global ?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@AEAH@Z
?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@AEAH@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 128]

global ?onRedstoneUpdate@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@H_N@Z
?onRedstoneUpdate@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@H_N@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 136]

global ?onLightningHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onLightningHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 144]

global ?liquidCanFlowIntoFromDirection@BlockLegacy@@UEAA_NEP6A?AV?$function@AEBVBlock@@@std@@AEBVBlockPos@@@Z@Z
?liquidCanFlowIntoFromDirection@BlockLegacy@@UEAA_NEP6A?AV?$function@AEBVBlock@@@std@@AEBVBlockPos@@@Z@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 152]

; BlockLegacy_vtable[20] is unknown
global ?_unknown_20@BlockLegacy@@UEAAXXZ
?_unknown_20@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 160]

; BlockLegacy_vtable[21] is unknown
global ?_unknown_21@BlockLegacy@@UEAAXXZ
?_unknown_21@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 168]

; BlockLegacy_vtable[22] is unknown
global ?_unknown_22@BlockLegacy@@UEAAXXZ
?_unknown_22@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 176]

global ?canProvideSupport@BlockLegacy@@UEBA_NAEBVBlock@@EW4BlockSupportType@@@Z
?canProvideSupport@BlockLegacy@@UEBA_NAEBVBlock@@EW4BlockSupportType@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 184]

global ?canProvideMultifaceSupport@BlockLegacy@@UEBA_NAEBVBlock@@E@Z
?canProvideMultifaceSupport@BlockLegacy@@UEBA_NAEBVBlock@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 192]

global ?canConnect@BlockLegacy@@UEBA_NAEBVBlock@@E0@Z
?canConnect@BlockLegacy@@UEBA_NAEBVBlock@@E0@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 200]

global ?tryGetCopperBehavior@BlockLegacy@@UEBAPEBVCopperBehavior@@XZ
?tryGetCopperBehavior@BlockLegacy@@UEBAPEBVCopperBehavior@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 208]

; BlockLegacy_vtable[27] is unknown
global ?_unknown_27@BlockLegacy@@UEAAXXZ
?_unknown_27@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 216]

; BlockLegacy_vtable[28] is unknown
global ?_unknown_28@BlockLegacy@@UEAAXXZ
?_unknown_28@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 224]

; BlockLegacy_vtable[29] is unknown
global ?_unknown_29@BlockLegacy@@UEAAXXZ
?_unknown_29@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 232]

; BlockLegacy_vtable[30] is unknown
global ?_unknown_30@BlockLegacy@@UEAAXXZ
?_unknown_30@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 240]

; BlockLegacy_vtable[31] is unknown
global ?_unknown_31@BlockLegacy@@UEAAXXZ
?_unknown_31@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 248]

global ?isWaterBlocking@BlockLegacy@@UEBA_NXZ
?isWaterBlocking@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 256]

; BlockLegacy_vtable[33] is unknown
global ?_unknown_33@BlockLegacy@@UEAAXXZ
?_unknown_33@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 264]

; BlockLegacy_vtable[34] is unknown
global ?_unknown_34@BlockLegacy@@UEAAXXZ
?_unknown_34@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 272]

; BlockLegacy_vtable[35] is unknown
global ?_unknown_35@BlockLegacy@@UEAAXXZ
?_unknown_35@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 280]

; BlockLegacy_vtable[36] is unknown
global ?_unknown_36@BlockLegacy@@UEAAXXZ
?_unknown_36@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 288]

global ?isStairBlock@BlockLegacy@@UEBA_NXZ
?isStairBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 296]

global ?isSlabBlock@BlockLegacy@@UEBA_NXZ
?isSlabBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 304]

global ?isDoubleSlabBlock@BlockLegacy@@UEBA_NXZ
?isDoubleSlabBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 312]

; BlockLegacy_vtable[40] is unknown
global ?_unknown_40@BlockLegacy@@UEAAXXZ
?_unknown_40@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 320]

; BlockLegacy_vtable[41] is unknown
global ?_unknown_41@BlockLegacy@@UEAAXXZ
?_unknown_41@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 328]

; BlockLegacy_vtable[42] is unknown
global ?_unknown_42@BlockLegacy@@UEAAXXZ
?_unknown_42@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 336]

; BlockLegacy_vtable[43] is unknown
global ?_unknown_43@BlockLegacy@@UEAAXXZ
?_unknown_43@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 344]

; BlockLegacy_vtable[44] is unknown
global ?_unknown_44@BlockLegacy@@UEAAXXZ
?_unknown_44@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 352]

; BlockLegacy_vtable[45] is unknown
global ?_unknown_45@BlockLegacy@@UEAAXXZ
?_unknown_45@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 360]

; BlockLegacy_vtable[46] is unknown
global ?_unknown_46@BlockLegacy@@UEAAXXZ
?_unknown_46@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 368]

global ?canBeOriginalSurface@BlockLegacy@@UEBA_NXZ
?canBeOriginalSurface@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 376]

; BlockLegacy_vtable[48] is unknown
global ?_unknown_48@BlockLegacy@@UEAAXXZ
?_unknown_48@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 384]

global ?isValidAuxValue@BlockLegacy@@UEBA_NH@Z
?isValidAuxValue@BlockLegacy@@UEBA_NH@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 392]

global ?canFillAtPos@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?canFillAtPos@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 400]

global ?sanitizeFillBlock@BlockLegacy@@UEBAAEBVBlock@@AEBV2@@Z
?sanitizeFillBlock@BlockLegacy@@UEBAAEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 408]

global ?onFillBlock@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?onFillBlock@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 416]

global ?getDirectSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@H@Z
?getDirectSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@H@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 424]

; BlockLegacy_vtable[54] is unknown
global ?_unknown_54@BlockLegacy@@UEAAXXZ
?_unknown_54@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 432]

; BlockLegacy_vtable[55] is unknown
global ?_unknown_55@BlockLegacy@@UEAAXXZ
?_unknown_55@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 440]

global ?canContainLiquid@BlockLegacy@@UEBA_NXZ
?canContainLiquid@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 448]

global ?getRequiredMedium@BlockLegacy@@UEBA?AV?$optional@VHashedString@@@std@@XZ
?getRequiredMedium@BlockLegacy@@UEBA?AV?$optional@VHashedString@@@std@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 456]

global ?shouldConnectToRedstone@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@W4Type@Direction@@@Z
?shouldConnectToRedstone@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@W4Type@Direction@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 464]

global ?handlePrecipitation@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@MM@Z
?handlePrecipitation@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@MM@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 472]

global ?canBeUsedInCommands@BlockLegacy@@UEBA_NAEBVBaseGameVersion@@@Z
?canBeUsedInCommands@BlockLegacy@@UEBA_NAEBVBaseGameVersion@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 480]

global ?checkIsPathable@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@1@Z
?checkIsPathable@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@1@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 488]

global ?shouldDispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@@Z
?shouldDispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 496]

global ?dispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z
?dispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 504]

global ?transformOnFall@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@M@Z
?transformOnFall@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@M@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 512]

; BlockLegacy_vtable[65] is unknown
global ?_unknown_65@BlockLegacy@@UEAAXXZ
?_unknown_65@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 520]

global ?onMove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z
?onMove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 528]

; BlockLegacy_vtable[67] is unknown
global ?_unknown_67@BlockLegacy@@UEAAXXZ
?_unknown_67@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 536]

global ?movedByPiston@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?movedByPiston@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 544]

global ?onStructureBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onStructureBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 552]

global ?onStructureNeighborBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onStructureNeighborBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 560]

global ?setupRedstoneComponent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?setupRedstoneComponent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 568]

global ?getRedstoneProperty@BlockLegacy@@UEBA?AW4BlockProperty@@AEAVBlockSource@@AEBVBlockPos@@@Z
?getRedstoneProperty@BlockLegacy@@UEBA?AW4BlockProperty@@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 576]

global ?updateEntityAfterFallOn@BlockLegacy@@UEBAXAEBVBlockPos@@AEAUUpdateEntityAfterFallOnInterface@@@Z
?updateEntityAfterFallOn@BlockLegacy@@UEBAXAEBVBlockPos@@AEAUUpdateEntityAfterFallOnInterface@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 584]

; BlockLegacy_vtable[74] is unknown
global ?_unknown_74@BlockLegacy@@UEAAXXZ
?_unknown_74@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 592]

global ?isPreservingMediumWhenPlaced@BlockLegacy@@UEBA_NPEBV1@@Z
?isPreservingMediumWhenPlaced@BlockLegacy@@UEBA_NPEBV1@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 600]

global ?isFilteredOut@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z
?isFilteredOut@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 608]

global ?canRenderSelectionOverlay@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z
?canRenderSelectionOverlay@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 616]

global ?ignoreEntitiesOnPistonMove@BlockLegacy@@UEBA_NAEBVBlock@@@Z
?ignoreEntitiesOnPistonMove@BlockLegacy@@UEBA_NAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 624]

global ?onFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@W4FertilizerType@@@Z
?onFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@W4FertilizerType@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 632]

global ?mayConsumeFertilizer@BlockLegacy@@UEBA_NAEAVBlockSource@@@Z
?mayConsumeFertilizer@BlockLegacy@@UEBA_NAEAVBlockSource@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 640]

global ?canBeFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?canBeFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 648]

global ?mayPick@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlock@@_N@Z
?mayPick@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlock@@_N@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 656]

global ?mayPick@BlockLegacy@@UEBA_NXZ
?mayPick@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 664]

global ?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 672]

global ?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@E@Z
?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 680]

global ?mayPlaceOn@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?mayPlaceOn@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 688]

global ?tryToPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEBUActorBlockSyncMessage@@@Z
?tryToPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEBUActorBlockSyncMessage@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 696]

global ?tryToTill@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@AEAVItemStack@@@Z
?tryToTill@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@AEAVItemStack@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 704]

global ?breaksFallingBlocks@BlockLegacy@@UEBA_NAEBVBlock@@VBaseGameVersion@@@Z
?breaksFallingBlocks@BlockLegacy@@UEBA_NAEBVBlock@@VBaseGameVersion@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 712]

global ?destroy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEAVActor@@@Z
?destroy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 720]

global ?getIgnoresDestroyPermissions@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@@Z
?getIgnoresDestroyPermissions@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 728]

global ?neighborChanged@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z
?neighborChanged@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 736]

global ?getSecondPart@BlockLegacy@@UEBA_NAEBVIConstBlockSource@@AEBVBlockPos@@AEAV3@@Z
?getSecondPart@BlockLegacy@@UEBA_NAEBVIConstBlockSource@@AEBVBlockPos@@AEAV3@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 744]

global ?playerWillDestroy@BlockLegacy@@UEBAPEBVBlock@@AEAVPlayer@@AEBVBlockPos@@AEBV2@@Z
?playerWillDestroy@BlockLegacy@@UEBAPEBVBlock@@AEAVPlayer@@AEBVBlockPos@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 752]

global ?asItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@PEBVBlockActor@@@Z
?asItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@PEBVBlockActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 760]

global ?trySpawnResourcesOnExplosion@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@M@Z
?trySpawnResourcesOnExplosion@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@M@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 768]

global ?getPlacementBlock@BlockLegacy@@UEBAAEBVBlock@@AEBVActor@@AEBVBlockPos@@EAEBVVec3@@H@Z
?getPlacementBlock@BlockLegacy@@UEBAAEBVBlock@@AEBVActor@@AEBVBlockPos@@EAEBVVec3@@H@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 776]

global ?calcVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVColor@mce@@@Z
?calcVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVColor@mce@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 784]

global ?isAttachedTo@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAV3@@Z
?isAttachedTo@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAV3@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 792]

global ?attack@BlockLegacy@@UEBA_NPEAVPlayer@@AEBVBlockPos@@@Z
?attack@BlockLegacy@@UEBA_NPEAVPlayer@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 800]

global ?shouldTriggerEntityInside@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z
?shouldTriggerEntityInside@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 808]

global ?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 816]

global ?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlockItem@@@Z
?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlockItem@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 824]

global ?triggerEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@HH@Z
?triggerEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@HH@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 832]

global ?executeEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVActor@@@Z
?executeEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 840]

global ?getMobToSpawn@BlockLegacy@@UEBAPEBVMobSpawnerData@@AEBVSpawnConditions@@AEAVBlockSource@@@Z
?getMobToSpawn@BlockLegacy@@UEBAPEBVMobSpawnerData@@AEBVSpawnConditions@@AEAVBlockSource@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 848]

global ?shouldStopFalling@BlockLegacy@@UEBA_NAEAVActor@@@Z
?shouldStopFalling@BlockLegacy@@UEBA_NAEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 856]

; BlockLegacy_vtable[108] is unknown
global ?_unknown_108@BlockLegacy@@UEAAXXZ
?_unknown_108@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 864]

; BlockLegacy_vtable[109] is unknown
global ?_unknown_109@BlockLegacy@@UEAAXXZ
?_unknown_109@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 872]

; BlockLegacy_vtable[110] is unknown
global ?_unknown_110@BlockLegacy@@UEAAXXZ
?_unknown_110@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 880]

global ?getComparatorSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@E@Z
?getComparatorSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 888]

global ?canSlide@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?canSlide@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 896]

; BlockLegacy_vtable[113] is unknown
global ?_unknown_113@BlockLegacy@@UEAAXXZ
?_unknown_113@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 904]

global ?canSpawnAt@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@@Z
?canSpawnAt@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 912]

global ?notifySpawnedAt@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?notifySpawnedAt@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 920]

; BlockLegacy_vtable[116] is unknown
global ?_unknown_116@BlockLegacy@@UEAAXXZ
?_unknown_116@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 928]

global ?getIconYOffset@BlockLegacy@@UEBAHXZ
?getIconYOffset@BlockLegacy@@UEBAHXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 936]

global ?buildDescriptionId@BlockLegacy@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVBlock@@@Z
?buildDescriptionId@BlockLegacy@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 944]

global ?isAuxValueRelevantForPicking@BlockLegacy@@UEBA_NXZ
?isAuxValueRelevantForPicking@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 952]

global ?getColor@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?getColor@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 960]

global ?getColor@BlockLegacy@@UEBAHAEBVBlock@@@Z
?getColor@BlockLegacy@@UEBAHAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 968]

global ?getColorAtPos@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z
?getColorAtPos@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 976]

global ?getColorForParticle@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?getColorForParticle@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 984]

global ?isSeasonTinted@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z
?isSeasonTinted@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 992]

global ?onGraphicsModeChanged@BlockLegacy@@UEAAXAEBUBlockGraphicsModeChangeContext@@@Z
?onGraphicsModeChanged@BlockLegacy@@UEAAXAEBUBlockGraphicsModeChangeContext@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1000]

global ?getShadeBrightness@BlockLegacy@@UEBAMAEBVBlock@@@Z
?getShadeBrightness@BlockLegacy@@UEBAMAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1008]

global ?telemetryVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z
?telemetryVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1016]

global ?getVariant@BlockLegacy@@UEBAHAEBVBlock@@@Z
?getVariant@BlockLegacy@@UEBAHAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1024]

global ?canSpawnOn@BlockLegacy@@UEBA_NPEAVActor@@@Z
?canSpawnOn@BlockLegacy@@UEBA_NPEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1032]

global ?getRenderBlock@BlockLegacy@@UEBAAEBVBlock@@XZ
?getRenderBlock@BlockLegacy@@UEBAAEBVBlock@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1040]

global ?getMappedFace@BlockLegacy@@UEBAEEAEBVBlock@@@Z
?getMappedFace@BlockLegacy@@UEBAEEAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1048]

global ?getFaceFlip@BlockLegacy@@UEBA?AW4Flip@@EAEBVBlock@@@Z
?getFaceFlip@BlockLegacy@@UEBA?AW4Flip@@EAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1056]

global ?animateTickBedrockLegacy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?animateTickBedrockLegacy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1064]

global ?animateTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?animateTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1072]

global ?init@BlockLegacy@@UEAAAEAV1@XZ
?init@BlockLegacy@@UEAAAEAV1@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1080]

global ?getLightEmission@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z
?getLightEmission@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1088]

global ?tryLegacyUpgrade@BlockLegacy@@UEBAPEBVBlock@@G@Z
?tryLegacyUpgrade@BlockLegacy@@UEBAPEBVBlock@@G@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1096]

global ?dealsContactDamage@BlockLegacy@@UEBA_NAEBVActor@@AEBVBlock@@_N@Z
?dealsContactDamage@BlockLegacy@@UEBA_NAEBVActor@@AEBVBlock@@_N@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1104]

global ?tryGetInfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
?tryGetInfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1112]

global ?tryGetUninfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
?tryGetUninfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1120]

global ?_addHardCodedBlockComponents@BlockLegacy@@UEAAXAEBVExperiments@@@Z
?_addHardCodedBlockComponents@BlockLegacy@@UEAAXAEBVExperiments@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1128]

global ?onRemove@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onRemove@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1136]

global ?onExploded@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z
?onExploded@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1144]

global ?onStandOn@BlockLegacy@@MEBAXAEAVEntityContext@@AEBVBlockPos@@@Z
?onStandOn@BlockLegacy@@MEBAXAEAVEntityContext@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1152]

global ?onPlace@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onPlace@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1160]

; BlockLegacy_vtable[146] is unknown
global ?_unknown_146@BlockLegacy@@MEAAXXZ
?_unknown_146@BlockLegacy@@MEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1168]

global ?tick@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?tick@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1176]

global ?randomTick@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?randomTick@BlockLegacy@@MEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1184]

; BlockLegacy_vtable[149] is unknown
global ?_unknown_149@BlockLegacy@@MEAAXXZ
?_unknown_149@BlockLegacy@@MEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1192]

global ?use@BlockLegacy@@MEBA_NAEAVPlayer@@AEBVBlockPos@@E@Z
?use@BlockLegacy@@MEBA_NAEAVPlayer@@AEBVBlockPos@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1200]

global ?use@BlockLegacy@@MEBA_NAEAVPlayer@@AEBVBlockPos@@EV?$optional@VVec3@@@std@@@Z
?use@BlockLegacy@@MEBA_NAEAVPlayer@@AEBVBlockPos@@EV?$optional@VVec3@@@std@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1208]

; BlockLegacy_vtable[152] is unknown
global ?_unknown_152@BlockLegacy@@MEAAXXZ
?_unknown_152@BlockLegacy@@MEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1216]

global ?canSurvive@BlockLegacy@@MEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?canSurvive@BlockLegacy@@MEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1224]

global ?getRenderLayer@BlockLegacy@@MEBA?AW4BlockRenderLayer@@AEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z
?getRenderLayer@BlockLegacy@@MEBA?AW4BlockRenderLayer@@AEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1232]

global ?getRenderLayer@BlockLegacy@@MEBA?AW4BlockRenderLayer@@XZ
?getRenderLayer@BlockLegacy@@MEBA?AW4BlockRenderLayer@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1240]

global ?getExtraRenderLayers@BlockLegacy@@MEBAHXZ
?getExtraRenderLayers@BlockLegacy@@MEBAHXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1248]

global ?getLight@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z
?getLight@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1256]

global ?getEmissiveBrightness@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z
?getEmissiveBrightness@BlockLegacy@@MEBA?AUBrightness@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1264]

global ?getMapColor@BlockLegacy@@MEBA?AVColor@mce@@AEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?getMapColor@BlockLegacy@@MEBA?AVColor@mce@@AEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1272]

global ?_onHitByActivatingAttack@BlockLegacy@@EEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z
?_onHitByActivatingAttack@BlockLegacy@@EEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1280]

global ?_spawnAfterBreak@BlockLegacy@@EEBAXAEAVBlockSource@@AEBVBlock@@AEBVBlockPos@@AEBUResourceDropsContext@@@Z
?_spawnAfterBreak@BlockLegacy@@EEBAXAEAVBlockSource@@AEBVBlock@@AEBVBlockPos@@AEBUResourceDropsContext@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1288]

global ?entityInside@BlockLegacy@@EEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z
?entityInside@BlockLegacy@@EEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1296]