; Automatically generated by FrederoxDev/Reverse-Tools/CxxParser/HeaderGenerator.py
section .text

extern BlockLegacy_vtable
extern BlockLegacy_ctor

global ??0BlockLegacy@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@FAEBVMaterial@@@Z
??0BlockLegacy@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@FAEBVMaterial@@@Z:
    mov rax, [rel BlockLegacy_ctor]
    jmp rax

global ?newBlockEntity@BlockLegacy@@UEBA?AV?$shared_ptr@VBlockActor@@@std@@AEBVBlockPos@@AEBVBlock@@@Z
?newBlockEntity@BlockLegacy@@UEBA?AV?$shared_ptr@VBlockActor@@@std@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 8]

global ?getNextBlockPermutation@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
?getNextBlockPermutation@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 16]

global ?clip@BlockLegacy@@UEBA?AVHitResult@@AEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@AEBVVec3@@3W4ShapeType@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
?clip@BlockLegacy@@UEBA?AVHitResult@@AEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@AEBVVec3@@3W4ShapeType@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 24]

global ?getCollisionShape@BlockLegacy@@UEBA?AVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
?getCollisionShape@BlockLegacy@@UEBA?AVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 32]

global ?getCollisionShapeForCamera@BlockLegacy@@UEBA_NAEAVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@@Z
?getCollisionShapeForCamera@BlockLegacy@@UEBA_NAEAVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 40]

global ?addCollisionShapes@BlockLegacy@@UEBA_NAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z
?addCollisionShapes@BlockLegacy@@UEBA_NAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@V?$optional_ref@$$CBVGetCollisionShapeInterface@@@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 48]

global ?addAABBs@BlockLegacy@@UEBAXAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@@Z
?addAABBs@BlockLegacy@@UEBAXAEBVBlock@@AEBVBlockSource@@AEBVBlockPos@@PEBVAABB@@AEAV?$vector@VAABB@@V?$allocator@VAABB@@@std@@@std@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 56]

global ?getOutline@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z
?getOutline@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 64]

global ?getVisualShapeInWorld@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z
?getVisualShapeInWorld@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEBVIConstBlockSource@@AEBVBlockPos@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 72]

global ?getVisualShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z
?getVisualShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 80]

global ?getUIShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z
?getUIShape@BlockLegacy@@UEBAAEBVAABB@@AEBVBlock@@AEAV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 88]

global ?getLiquidClipVolume@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEAVAABB@@@Z
?getLiquidClipVolume@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEAVAABB@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 96]

global ?isObstructingChests@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?isObstructingChests@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 104]

global ?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@@Z
?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 112]

global ?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@AEAH@Z
?randomlyModifyPosition@BlockLegacy@@UEBA?AVVec3@@AEBVBlockPos@@AEAH@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 120]

global ?onProjectileHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVActor@@@Z
?onProjectileHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 128]

global ?onLightningHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onLightningHit@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 136]

global ?liquidCanFlowIntoFromDirection@BlockLegacy@@UEBA_NEV?$function@$$A6AAEBVBlock@@AEBVBlockPos@@@Z@std@@AEBVBlockPos@@@Z
?liquidCanFlowIntoFromDirection@BlockLegacy@@UEBA_NEV?$function@$$A6AAEBVBlock@@AEBVBlockPos@@@Z@std@@AEBVBlockPos@@@Z:
    mov rax, [rel BlockLegacy_vtable]
    jmp [rax + 144]

global ?hasVariableLighting@BlockLegacy@@UEBA_NXZ
?hasVariableLighting@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 152]

global ?isStrippable@BlockLegacy@@UEBA_NAEBVBlock@@@Z
?isStrippable@BlockLegacy@@UEBA_NAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 160]

global ?getStrippedBlock@BlockLegacy@@UEBAAEBVBlock@@AEBV2@@Z
?getStrippedBlock@BlockLegacy@@UEBAAEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 168]

global ?canProvideSupport@BlockLegacy@@UEBA_NAEBVBlock@@EW4BlockSupportType@@@Z
?canProvideSupport@BlockLegacy@@UEBA_NAEBVBlock@@EW4BlockSupportType@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 176]

global ?canProvideMultifaceSupport@BlockLegacy@@UEBA_NAEBVBlock@@E@Z
?canProvideMultifaceSupport@BlockLegacy@@UEBA_NAEBVBlock@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 184]

global ?canConnect@BlockLegacy@@UEBA_NAEBVBlock@@E0@Z
?canConnect@BlockLegacy@@UEBA_NAEBVBlock@@E0@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 192]

global ?tryGetCopperBehavior@BlockLegacy@@UEBAPEBVCopperBehavior@@XZ
?tryGetCopperBehavior@BlockLegacy@@UEBAPEBVCopperBehavior@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 200]

global ?canDamperVibrations@BlockLegacy@@UEBA_NXZ
?canDamperVibrations@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 208]

global ?canOccludeVibrations@BlockLegacy@@UEBA_NXZ
?canOccludeVibrations@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 216]

global ?isStemBlock@BlockLegacy@@UEBA_NXZ
?isStemBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 224]

global ?isContainerBlock@BlockLegacy@@UEBA_NXZ
?isContainerBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 232]

global ?isCraftingBlock@BlockLegacy@@UEBA_NXZ
?isCraftingBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 240]

global ?isWaterBlocking@BlockLegacy@@UEBA_NXZ
?isWaterBlocking@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 248]

global ?isFenceBlock@BlockLegacy@@UEBA_NXZ
?isFenceBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 256]

global ?isFenceGateBlock@BlockLegacy@@UEBA_NXZ
?isFenceGateBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 264]

global ?isThinFenceBlock@BlockLegacy@@UEBA_NXZ
?isThinFenceBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 272]

global ?isWallBlock@BlockLegacy@@UEBA_NXZ
?isWallBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 280]

global ?isStairBlock@BlockLegacy@@UEBA_NXZ
?isStairBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 288]

global ?isSlabBlock@BlockLegacy@@UEBA_NXZ
?isSlabBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 296]

global ?isDoubleSlabBlock@BlockLegacy@@UEBA_NXZ
?isDoubleSlabBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 304]

global ?isDoorBlock@BlockLegacy@@UEBA_NXZ
?isDoorBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 312]

global ?isRailBlock@BlockLegacy@@UEBA_NXZ
?isRailBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 320]

global ?isButtonBlock@BlockLegacy@@UEBA_NXZ
?isButtonBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 328]

global ?isLeverBlock@BlockLegacy@@UEBA_NXZ
?isLeverBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 336]

global ?isCandleCakeBlock@BlockLegacy@@UEBA_NXZ
?isCandleCakeBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 344]

global ?isMultifaceBlock@BlockLegacy@@UEBA_NXZ
?isMultifaceBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 352]

global ?isSignalSource@BlockLegacy@@UEBA_NXZ
?isSignalSource@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 360]

global ?canBeOriginalSurface@BlockLegacy@@UEBA_NXZ
?canBeOriginalSurface@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 368]

global ?isSilentWhenJumpingOff@BlockLegacy@@UEBA_NXZ
?isSilentWhenJumpingOff@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 376]

global ?isValidAuxValue@BlockLegacy@@UEBA_NH@Z
?isValidAuxValue@BlockLegacy@@UEBA_NH@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 384]

global ?canFillAtPos@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?canFillAtPos@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 392]

global ?sanitizeFillBlock@BlockLegacy@@UEBAAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEBV2@@Z
?sanitizeFillBlock@BlockLegacy@@UEBAAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 400]

global ?onFillBlock@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?onFillBlock@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 408]

global ?getDirectSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@H@Z
?getDirectSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@H@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 416]

global ?canBeDestroyedByWaterSpread@BlockLegacy@@UEBA_NXZ
?canBeDestroyedByWaterSpread@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 424]

global ?waterSpreadCausesSpawn@BlockLegacy@@UEBA_NXZ
?waterSpreadCausesSpawn@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 432]

global ?canContainLiquid@BlockLegacy@@UEBA_NXZ
?canContainLiquid@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 440]

global ?getRequiredMedium@BlockLegacy@@UEBA?AV?$optional@VHashedString@@@std@@XZ
?getRequiredMedium@BlockLegacy@@UEBA?AV?$optional@VHashedString@@@std@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 448]

global ?shouldConnectToRedstone@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@W4Type@Direction@@@Z
?shouldConnectToRedstone@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@W4Type@Direction@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 456]

global ?handlePrecipitation@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@MM@Z
?handlePrecipitation@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@MM@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 464]

global ?canBeUsedInCommands@BlockLegacy@@UEBA_NAEBVBaseGameVersion@@@Z
?canBeUsedInCommands@BlockLegacy@@UEBA_NAEBVBaseGameVersion@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 472]

global ?checkIsPathable@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@1@Z
?checkIsPathable@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@1@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 480]

global ?shouldDispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@@Z
?shouldDispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 488]

global ?dispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z
?dispense@BlockLegacy@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 496]

global ?transformOnFall@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@M@Z
?transformOnFall@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@M@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 504]

global ?onRedstoneUpdate@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@H_N@Z
?onRedstoneUpdate@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@H_N@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 512]

global ?onMove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z
?onMove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 520]

global ?detachesOnPistonMove@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?detachesOnPistonMove@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 528]

global ?movedByPiston@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?movedByPiston@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 536]

global ?onStructureBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onStructureBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 544]

global ?onStructureNeighborBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onStructureNeighborBlockPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 552]

global ?setupRedstoneComponent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?setupRedstoneComponent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 560]

global ?getRedstoneProperty@BlockLegacy@@UEBA?AW4BlockProperty@@AEAVBlockSource@@AEBVBlockPos@@@Z
?getRedstoneProperty@BlockLegacy@@UEBA?AW4BlockProperty@@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 568]

global ?updateEntityAfterFallOn@BlockLegacy@@UEBAXAEBVBlockPos@@AEAUUpdateEntityAfterFallOnInterface@@@Z
?updateEntityAfterFallOn@BlockLegacy@@UEBAXAEBVBlockPos@@AEAUUpdateEntityAfterFallOnInterface@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 576]

global ?isBounceBlock@BlockLegacy@@UEBA_NXZ
?isBounceBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 584]

global ?isPreservingMediumWhenPlaced@BlockLegacy@@UEBA_NPEBV1@@Z
?isPreservingMediumWhenPlaced@BlockLegacy@@UEBA_NPEBV1@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 592]

global ?isFilteredOut@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z
?isFilteredOut@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 600]

global ?canRenderSelectionOverlay@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z
?canRenderSelectionOverlay@BlockLegacy@@UEBA_NW4BlockRenderLayer@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 608]

global ?ignoreEntitiesOnPistonMove@BlockLegacy@@UEBA_NAEBVBlock@@@Z
?ignoreEntitiesOnPistonMove@BlockLegacy@@UEBA_NAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 616]

global ?onFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@W4FertilizerType@@@Z
?onFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@W4FertilizerType@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 624]

global ?mayConsumeFertilizer@BlockLegacy@@UEBA_NAEAVBlockSource@@@Z
?mayConsumeFertilizer@BlockLegacy@@UEBA_NAEAVBlockSource@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 632]

global ?canBeFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?canBeFertilized@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 640]

global ?mayPick@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlock@@_N@Z
?mayPick@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlock@@_N@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 648]

global ?mayPick@BlockLegacy@@UEBA_NXZ
?mayPick@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 656]

global ?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 664]

global ?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@E@Z
?mayPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 672]

global ?mayPlaceOn@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?mayPlaceOn@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 680]

global ?tryToPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEBUActorBlockSyncMessage@@@Z
?tryToPlace@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEBUActorBlockSyncMessage@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 688]

global ?tryToTill@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@AEAVItemStack@@@Z
?tryToTill@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@AEAVItemStack@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 696]

global ?breaksFallingBlocks@BlockLegacy@@UEBA_NAEBVBlock@@VBaseGameVersion@@@Z
?breaksFallingBlocks@BlockLegacy@@UEBA_NAEBVBlock@@VBaseGameVersion@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 704]

global ?destroy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEAVActor@@@Z
?destroy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@PEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 712]

global ?getIgnoresDestroyPermissions@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@@Z
?getIgnoresDestroyPermissions@BlockLegacy@@UEBA_NAEAVActor@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 720]

global ?neighborChanged@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z
?neighborChanged@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@1@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 728]

global ?getSecondPart@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@AEAV3@@Z
?getSecondPart@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@AEAV3@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 736]

global ?playerWillDestroy@BlockLegacy@@UEBAPEBVBlock@@AEAVPlayer@@AEBVBlockPos@@AEBV2@@Z
?playerWillDestroy@BlockLegacy@@UEBAPEBVBlock@@AEAVPlayer@@AEBVBlockPos@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 744]

global ?spawnResources@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@AEBUResourceDropsContext@@@Z
?spawnResources@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@AEBUResourceDropsContext@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 752]

global ?asItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@PEBVBlockActor@@@Z
?asItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@PEBVBlockActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 760]

global ?trySpawnResourcesOnExplosion@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@M@Z
?trySpawnResourcesOnExplosion@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEAVRandomize@@M@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 768]

global ?getPlacementBlock@BlockLegacy@@UEBAAEBVBlock@@AEBVActor@@AEBVBlockPos@@EAEBVVec3@@H@Z
?getPlacementBlock@BlockLegacy@@UEBAAEBVBlock@@AEBVActor@@AEBVBlockPos@@EAEBVVec3@@H@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 776]

global ?calcVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVColor@mce@@@Z
?calcVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVColor@mce@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 784]

global ?isAttachedTo@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAV3@@Z
?isAttachedTo@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAV3@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 792]

global ?attack@BlockLegacy@@UEBA_NPEAVPlayer@@AEBVBlockPos@@@Z
?attack@BlockLegacy@@UEBA_NPEAVPlayer@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 800]

global ?shouldTriggerEntityInside@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z
?shouldTriggerEntityInside@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 808]

global ?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 816]

global ?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlockItem@@@Z
?canBeBuiltOver@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlockItem@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 824]

global ?triggerEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@HH@Z
?triggerEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@HH@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 832]

global ?executeEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVActor@@@Z
?executeEvent@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 840]

global ?hasTag@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
?hasTag@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 848]

global ?getMobToSpawn@BlockLegacy@@UEBAPEBVMobSpawnerData@@AEBVSpawnConditions@@AEAVBlockSource@@@Z
?getMobToSpawn@BlockLegacy@@UEBAPEBVMobSpawnerData@@AEBVSpawnConditions@@AEAVBlockSource@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 856]

global ?shouldStopFalling@BlockLegacy@@UEBA_NAEAVActor@@@Z
?shouldStopFalling@BlockLegacy@@UEBA_NAEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 864]

global ?pushesUpFallingBlocks@BlockLegacy@@UEBA_NXZ
?pushesUpFallingBlocks@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 872]

global ?canHaveExtraData@BlockLegacy@@UEBA_NXZ
?canHaveExtraData@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 880]

global ?hasComparatorSignal@BlockLegacy@@UEBA_NXZ
?hasComparatorSignal@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 888]

global ?getComparatorSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@E@Z
?getComparatorSignal@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 896]

global ?canSlide@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?canSlide@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 904]

global ?canInstatick@BlockLegacy@@UEBA_NXZ
?canInstatick@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 912]

global ?canSpawnAt@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@@Z
?canSpawnAt@BlockLegacy@@UEBA_NAEBVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 920]

global ?notifySpawnedAt@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?notifySpawnedAt@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 928]

global ?causesFreezeEffect@BlockLegacy@@UEBA_NXZ
?causesFreezeEffect@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 936]

global ?getIconYOffset@BlockLegacy@@UEBAHXZ
?getIconYOffset@BlockLegacy@@UEBAHXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 944]

global ?buildDescriptionId@BlockLegacy@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVBlock@@@Z
?buildDescriptionId@BlockLegacy@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 952]

global ?isAuxValueRelevantForPicking@BlockLegacy@@UEBA_NXZ
?isAuxValueRelevantForPicking@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 960]

global ?getColor@BlockLegacy@@UEBAHAEBVBlock@@@Z
?getColor@BlockLegacy@@UEBAHAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 968]

global ?getColorAtPos@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z
?getColorAtPos@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 976]

global ?getColor@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?getColor@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 984]

global ?getColorForParticle@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?getColorForParticle@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 992]

global ?isSeasonTinted@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z
?isSeasonTinted@BlockLegacy@@UEBA_NAEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1000]

global ?onGraphicsModeChanged@BlockLegacy@@UEAAXAEBUBlockGraphicsModeChangeContext@@@Z
?onGraphicsModeChanged@BlockLegacy@@UEAAXAEBUBlockGraphicsModeChangeContext@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1008]

global ?getShadeBrightness@BlockLegacy@@UEBAMAEBVBlock@@@Z
?getShadeBrightness@BlockLegacy@@UEBAMAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1016]

global ?telemetryVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z
?telemetryVariant@BlockLegacy@@UEBAHAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1024]

global ?getVariant@BlockLegacy@@UEBAHAEBVBlock@@@Z
?getVariant@BlockLegacy@@UEBAHAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1032]

global ?canSpawnOn@BlockLegacy@@UEBA_NPEAVActor@@@Z
?canSpawnOn@BlockLegacy@@UEBA_NPEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1040]

global ?getRenderBlock@BlockLegacy@@UEBAAEBVBlock@@XZ
?getRenderBlock@BlockLegacy@@UEBAAEBVBlock@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1048]

global ?getMappedFace@BlockLegacy@@UEBAEEAEBVBlock@@@Z
?getMappedFace@BlockLegacy@@UEBAEEAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1056]

global ?getFaceFlip@BlockLegacy@@UEBA?AW4Flip@@EAEBVBlock@@@Z
?getFaceFlip@BlockLegacy@@UEBA?AW4Flip@@EAEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1064]

global ?animateTickBedrockLegacy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?animateTickBedrockLegacy@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1072]

global ?animateTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?animateTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1080]

global ?init@BlockLegacy@@UEAAAEAV1@XZ
?init@BlockLegacy@@UEAAAEAV1@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1088]

global ?canBeSilkTouched@BlockLegacy@@UEBA_NXZ
?canBeSilkTouched@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1096]

global ?tryLegacyUpgrade@BlockLegacy@@UEBAPEBVBlock@@G@Z
?tryLegacyUpgrade@BlockLegacy@@UEBAPEBVBlock@@G@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1104]

global ?dealsContactDamage@BlockLegacy@@UEBA_NAEBVActor@@AEBVBlock@@_N@Z
?dealsContactDamage@BlockLegacy@@UEBA_NAEBVActor@@AEBVBlock@@_N@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1112]

global ?tryGetInfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
?tryGetInfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1120]

global ?tryGetUninfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z
?tryGetUninfested@BlockLegacy@@UEBAPEBVBlock@@AEBV2@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1128]

global ?_addHardCodedBlockComponents@BlockLegacy@@UEAAXXZ
?_addHardCodedBlockComponents@BlockLegacy@@UEAAXXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1136]

global ?onRemove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onRemove@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1144]

global ?onExploded@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z
?onExploded@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@PEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1152]

global ?onStandOn@BlockLegacy@@UEBAXAEAVEntityContext@@AEBVBlockPos@@@Z
?onStandOn@BlockLegacy@@UEBAXAEAVEntityContext@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1160]

global ?onPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z
?onPlace@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1168]

global ?onFallOn@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@M@Z
?onFallOn@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@M@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1176]

global ?shouldTickOnSetBlock@BlockLegacy@@UEBA_NXZ
?shouldTickOnSetBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1184]

global ?tick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?tick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1192]

global ?randomTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z
?randomTick@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVRandom@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1200]

global ?isInteractiveBlock@BlockLegacy@@UEBA_NXZ
?isInteractiveBlock@BlockLegacy@@UEBA_NXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1208]

global ?use@BlockLegacy@@UEBA_NAEAVPlayer@@AEBVBlockPos@@E@Z
?use@BlockLegacy@@UEBA_NAEAVPlayer@@AEBVBlockPos@@E@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1216]

global ?use@BlockLegacy@@UEBA_NAEAVPlayer@@AEBVBlockPos@@EV?$optional@VVec3@@@std@@@Z
?use@BlockLegacy@@UEBA_NAEAVPlayer@@AEBVBlockPos@@EV?$optional@VVec3@@@std@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1224]

global ?allowStateMismatchOnPlacement@BlockLegacy@@UEBA_NAEBVBlock@@0@Z
?allowStateMismatchOnPlacement@BlockLegacy@@UEBA_NAEBVBlock@@0@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1232]

global ?canSurvive@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z
?canSurvive@BlockLegacy@@UEBA_NAEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1240]

global ?getRenderLayer@BlockLegacy@@UEBA?AW4BlockRenderLayer@@AEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z
?getRenderLayer@BlockLegacy@@UEBA?AW4BlockRenderLayer@@AEBVBlock@@AEAVBlockSource@@AEBVBlockPos@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1248]

global ?getRenderLayer@BlockLegacy@@UEBA?AW4BlockRenderLayer@@XZ
?getRenderLayer@BlockLegacy@@UEBA?AW4BlockRenderLayer@@XZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1256]

global ?getExtraRenderLayers@BlockLegacy@@UEBAHXZ
?getExtraRenderLayers@BlockLegacy@@UEBAHXZ:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1264]

global ?getLight@BlockLegacy@@UEBA?AUBrightness@@AEBVBlock@@@Z
?getLight@BlockLegacy@@UEBA?AUBrightness@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1272]

global ?getLightEmission@BlockLegacy@@UEBA?AUBrightness@@AEBVBlock@@@Z
?getLightEmission@BlockLegacy@@UEBA?AUBrightness@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1280]

global ?getEmissiveBrightness@BlockLegacy@@UEBA?AUBrightness@@AEBVBlock@@@Z
?getEmissiveBrightness@BlockLegacy@@UEBA?AUBrightness@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1288]

global ?getMapColor@BlockLegacy@@UEBA?AVColor@mce@@AEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z
?getMapColor@BlockLegacy@@UEBA?AVColor@mce@@AEAVBlockSource@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1296]

global ?playerDestroy@BlockLegacy@@UEBAXAEAVPlayer@@AEBVBlockPos@@AEBVBlock@@@Z
?playerDestroy@BlockLegacy@@UEBAXAEAVPlayer@@AEBVBlockPos@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1304]

global ?getResourceItem@BlockLegacy@@UEBA?AVItemInstance@@AEAVRandomize@@AEBVBlock@@H@Z
?getResourceItem@BlockLegacy@@UEBA?AVItemInstance@@AEAVRandomize@@AEBVBlock@@H@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1312]

global ?getResourceCount@BlockLegacy@@UEBAHAEAVRandomize@@AEBVBlock@@H@Z
?getResourceCount@BlockLegacy@@UEBAHAEAVRandomize@@AEBVBlock@@H@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1320]

global ?getSilkTouchItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@@Z
?getSilkTouchItemInstance@BlockLegacy@@UEBA?AVItemInstance@@AEBVBlock@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1328]

global ?entityInside@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z
?entityInside@BlockLegacy@@UEBAXAEAVBlockSource@@AEBVBlockPos@@AEAVActor@@@Z:
	mov rax, [rel BlockLegacy_vtable]
	jmp [rax + 1336]