#pragma once

enum class LevelEvent : short {
    Undefined,
    SoundClick = 1000,
    SoundClickFail,
    SoundLaunch,
    SoundOpenDoor,
    SoundFizz,
    SoundFuse,
    SoundPlayRecording,
    SoundGhastWarning,
    SoundGhastFireball,
    SoundBlazeFireball,
    SoundZombieWoodenDoor,
    SoundZombieDoorCrash = 1012,
    SoundZombieInfected = 1016,
    SoundZombieConverted,
    SoundEndermanTeleport,
    SoundAnvilBroken = 1020,
    SoundAnvilUsed,
    SoundAnvilLand,
    SoundInfinityArrowPickup = 1030,
    SoundTeleportEnderPearl = 1032,
    SoundAddItem = 1040,
    SoundItemFrameBreak,
    SoundItemFramePlace,
    SoundItemFrameRemoveItem,
    SoundItemFrameRotateItem,
    SoundExperienceOrbPickup = 1051,
    SoundTotemUsed,
    SoundArmorStandBreak = 1060,
    SoundArmorStandHit,
    SoundArmorStandLand,
    SoundArmorStandPlace,
    SoundPointedDripstoneLand,
    SoundDyeUsed,
    SoundInkSacUsed,
    QueueCustomMusic = 1900,
    PlayCustomMusic,
    StopCustomMusic,
    SetMusicVolume,
    ParticlesShoot = 2000,
    ParticlesDestroyBlock,
    ParticlesPotionSplash,
    ParticlesEyeOfEnderDeath,
    ParticlesMobBlockSpawn,
    ParticleCropGrowth,
    ParticleSoundGuardianGhost,
    ParticleDeathSmoke,
    ParticleDenyBlock,
    ParticleGenericSpawn,
    ParticlesDragonEgg,
    ParticlesCropEaten,
    ParticlesCrit,
    ParticlesTeleport,
    ParticlesCrackBlock,
    ParticlesBubble,
    ParticlesEvaporate,
    ParticlesDestroyArmorStand,
    ParticlesBreakingEgg,
    ParticleDestroyEgg,
    ParticlesEvaporateWater,
    ParticlesDestroyBlockNoSound,
    ParticlesKnockbackRoar,
    ParticlesTeleportTrail,
    ParticlesPointCloud,
    ParticlesExplosion,
    ParticlesBlockExplosion,
    ParticlesVibrationSignal,
    ParticlesDripstoneDrip,
    ParticlesFizzEffect,
    WaxOn,
    WaxOff,
    Scrape,
    ParticlesElectricSpark,
    ParticleTurtleEgg,
    ParticlesSculkShriek,
    SculkCatalystBloom,
    SculkCharge,
    SculkChargePop,
    SonicExplosion,
    StartRaining = 3001,
    StartThunderstorm,
    StopRaining,
    StopThunderstorm,
    GlobalPause,
    SimTimeStep,
    SimTimeScale,
    ActivateBlock = 3500,
    CauldronExplode,
    CauldronDyeArmor,
    CauldronCleanArmor,
    CauldronFillPotion,
    CauldronTakePotion,
    CauldronFillWater,
    CauldronTakeWater,
    CauldronAddDye,
    CauldronCleanBanner,
    CauldronFlush,
    AgentSpawnEffect,
    CauldronFillLava,
    CauldronTakeLava,
    CauldronFillPowderSnow,
    CauldronTakePowderSnow,
    StartBlockCracking = 3600,
    StopBlockCracking,
    UpdateBlockCracking,
    AllPlayersSleeping = 9800,
    SleepingPlayers,
    JumpPrevented = 9810,
    ParticleLegacyEvent = 16384
};