; automatically generated by FrederoxDev/Header-Test
section .text

extern OverworldDimension_vtable
extern OverworldDimension_ctor

global ??_DOverworldDimension@@QEAAXXZ
??_DOverworldDimension@@QEAAXXZ:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 0]

global ?createGenerator@OverworldDimension@@UEAA?AV?$unique_ptr@VWorldGenerator@@U?$default_delete@VWorldGenerator@@@std@@@std@@AEBVStructureSetRegistry@worldgen@br@@@Z
?createGenerator@OverworldDimension@@UEAA?AV?$unique_ptr@VWorldGenerator@@U?$default_delete@VWorldGenerator@@@std@@@std@@AEBVStructureSetRegistry@worldgen@br@@@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 112]

global ?upgradeLevelChunk@OverworldDimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@1@Z
?upgradeLevelChunk@OverworldDimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@1@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 120]

global ?fixWallChunk@OverworldDimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@@Z
?fixWallChunk@OverworldDimension@@UEAAXAEAVChunkSource@@AEAVLevelChunk@@@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 128]

global ?levelChunkNeedsUpgrade@OverworldDimension@@UEBA_NAEBVLevelChunk@@@Z
?levelChunkNeedsUpgrade@OverworldDimension@@UEBA_NAEBVLevelChunk@@@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 136]

global ?getBrightnessDependentFogColor@OverworldDimension@@UEBA?AVColor@mce@@AEBV23@M@Z
?getBrightnessDependentFogColor@OverworldDimension@@UEBA?AVColor@mce@@AEBV23@M@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 152]

global ?getCloudHeight@OverworldDimension@@UEBAFXZ
?getCloudHeight@OverworldDimension@@UEBAFXZ:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 168]

global ?_upgradeOldLimboEntity@OverworldDimension@@UEAAXAEAVCompoundTag@@W4LimboEntitiesVersion@@@Z
?_upgradeOldLimboEntity@OverworldDimension@@UEAAXAEAVCompoundTag@@W4LimboEntitiesVersion@@@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 312]

global ?_wrapStorageForVersionCompatibility@OverworldDimension@@UEAA?AV?$unique_ptr@VChunkSource@@U?$default_delete@VChunkSource@@@std@@@std@@V23@W4StorageVersion@@@Z
?_wrapStorageForVersionCompatibility@OverworldDimension@@UEAA?AV?$unique_ptr@VChunkSource@@U?$default_delete@VChunkSource@@@std@@@std@@V23@W4StorageVersion@@@Z:
	mov rax, [rel OverworldDimension_vtable]
	jmp [rax + 320]

global ??0OverworldDimension@@QEAA@AEAVILevel@@V?$AutomaticID@VDimension@@H@@VDimensionHeightRange@@AEAVScheduler@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
??0OverworldDimension@@QEAA@AEAVILevel@@V?$AutomaticID@VDimension@@H@@VDimensionHeightRange@@AEAVScheduler@@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov rax, [rel OverworldDimension_ctor]
	jmp rax