; Automatically generated assembly for virtual function definitions
; generated by FrederoxDev/Virtual-Headers
section .text
extern Item_vtable

global ??_EItem@@UEAAPEAXI@Z
??_EItem@@UEAAPEAXI@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 0]

global ?initServer@Item@@UEAA_NAEAVValue@Json@@AEBVSemVersion@@_NAEBVExperiments@@@Z
?initServer@Item@@UEAA_NAEAVValue@Json@@AEBVSemVersion@@_NAEBVExperiments@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 8]

global ?tearDown@Item@@UEAAXXZ
?tearDown@Item@@UEAAXXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 16]

global ?setDescriptionId@Item@@UEAAAEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z
?setDescriptionId@Item@@UEAAAEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 24]

global ?getDescriptionId@Item@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
?getDescriptionId@Item@@UEBAAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 32]

global ?getMaxUseDuration@Item@@UEBAHPEBVItemStack@@@Z
?getMaxUseDuration@Item@@UEBAHPEBVItemStack@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 40]

global ?isMusicDisk@Item@@UEBA_NXZ
?isMusicDisk@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 48]

global ?executeEvent@Item@@UEBAXAEAVItemStackBase@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVRenderParams@@@Z
?executeEvent@Item@@UEBAXAEAVItemStackBase@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEAVRenderParams@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 56]

; Item_vtable[8] is unknown

global ?isArmor@Item@@UEBA_NXZ
?isArmor@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 72]

global ?isBlockPlanterItem@Item@@UEBA_NXZ
?isBlockPlanterItem@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 80]

; Item_vtable[11] is unknown

global ?isCandle@Item@@UEBA_NXZ
?isCandle@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 96]

global ?isDamageable@Item@@UEBA_NXZ
?isDamageable@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 104]

global ?isDyeable@Item@@UEBA_NXZ
?isDyeable@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 112]

global ?isDye@Item@@UEBA_NXZ
?isDye@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 120]

global ?getItemColor@Item@@UEBA?AW4ItemColor@@XZ
?getItemColor@Item@@UEBA?AW4ItemColor@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 128]

global ?isFertilizer@Item@@UEBA_NXZ
?isFertilizer@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 136]

global ?isFood@Item@@UEBA_NXZ
?isFood@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 144]

global ?isThrowable@Item@@UEBA_NXZ
?isThrowable@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 152]

global ?isUseable@Item@@UEBA_NXZ
?isUseable@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 160]

global ?isTrimAllowed@Item@@UEBA_NXZ
?isTrimAllowed@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 168]

global ?getComponent@Item@@UEBAPEAVItemComponent@@AEBVHashedString@@@Z
?getComponent@Item@@UEBAPEAVItemComponent@@AEBVHashedString@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 176]

global ?getFood@Item@@UEBAPEAVIFoodItemComponent@@XZ
?getFood@Item@@UEBAPEAVIFoodItemComponent@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 184]

global ?setMaxDamage@Item@@UEAAAEAV1@H@Z
?setMaxDamage@Item@@UEAAAEAV1@H@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 192]

global ?setMaxUseDuration@Item@@UEAAAEAV1@H@Z
?setMaxUseDuration@Item@@UEAAAEAV1@H@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 200]

global ?buildNetworkTag@Item@@UEBA?AV?$unique_ptr@VCompoundTag@@U?$default_delete@VCompoundTag@@@std@@@std@@XZ
?buildNetworkTag@Item@@UEBA?AV?$unique_ptr@VCompoundTag@@U?$default_delete@VCompoundTag@@@std@@@std@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 208]

global ?initializeFromNetwork@Item@@UEAAXAEBVCompoundTag@@@Z
?initializeFromNetwork@Item@@UEAAXAEBVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 216]

global ?validateFromNetwork@Item@@UEAA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVCompoundTag@@@Z
?validateFromNetwork@Item@@UEAA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@AEBVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 224]

global ?getBlockShape@Item@@UEBA?AW4BlockShape@@XZ
?getBlockShape@Item@@UEBA?AW4BlockShape@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 232]

global ?canBeDepleted@Item@@UEBA_NXZ
?canBeDepleted@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 240]

global ?canDestroySpecial@Item@@UEBA_NAEBVBlock@@@Z
?canDestroySpecial@Item@@UEBA_NAEBVBlock@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 248]

global ?getLevelDataForAuxValue@Item@@UEBAHH@Z
?getLevelDataForAuxValue@Item@@UEBAHH@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 256]

global ?isStackedByData@Item@@UEBA_NXZ
?isStackedByData@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 264]

global ?getMaxDamage@Item@@UEBAFXZ
?getMaxDamage@Item@@UEBAFXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 272]

global ?getAttackDamage@Item@@UEBAHXZ
?getAttackDamage@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 280]

global ?isHandEquipped@Item@@UEBA_NXZ
?isHandEquipped@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 288]

global ?isGlint@Item@@UEBA_NAEBVItemStackBase@@@Z
?isGlint@Item@@UEBA_NAEBVItemStackBase@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 296]

global ?isPattern@Item@@UEBA_NXZ
?isPattern@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 304]

global ?getPatternIndex@Item@@UEBAHXZ
?getPatternIndex@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 312]

; Item_vtable[40] is unknown

global ?isWearableThroughLootTable@Item@@UEBA_NPEBVCompoundTag@@@Z
?isWearableThroughLootTable@Item@@UEBA_NPEBVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 328]

global ?canDestroyInCreative@Item@@UEBA_NXZ
?canDestroyInCreative@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 336]

global ?isDestructive@Item@@UEBA_NH@Z
?isDestructive@Item@@UEBA_NH@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 344]

global ?isLiquidClipItem@Item@@UEBA_NXZ
?isLiquidClipItem@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 352]

global ?shouldInteractionWithBlockBypassLiquid@Item@@UEBA_NAEBVBlock@@@Z
?shouldInteractionWithBlockBypassLiquid@Item@@UEBA_NAEBVBlock@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 360]

global ?requiresInteract@Item@@UEBA_NXZ
?requiresInteract@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 368]

global ?appendFormattedHovertext@Item@@UEBAXAEBVItemStackBase@@AEAVLevel@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z
?appendFormattedHovertext@Item@@UEBAXAEBVItemStackBase@@AEAVLevel@@AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 376]

global ?isValidRepairItem@Item@@UEBA_NAEBVItemStackBase@@0AEBVBaseGameVersion@@@Z
?isValidRepairItem@Item@@UEBA_NAEBVItemStackBase@@0AEBVBaseGameVersion@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 384]

global ?getEnchantSlot@Item@@UEBAHXZ
?getEnchantSlot@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 392]

global ?getEnchantValue@Item@@UEBAHXZ
?getEnchantValue@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 400]

global ?getArmorValue@Item@@UEBAHXZ
?getArmorValue@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 408]

global ?getToughnessValue@Item@@UEBAHXZ
?getToughnessValue@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 416]

; Item_vtable[53] is unknown

global ?isValidAuxValue@Item@@UEBA_NH@Z
?isValidAuxValue@Item@@UEBA_NH@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 432]

global ?getDamageChance@Item@@UEBAHH@Z
?getDamageChance@Item@@UEBAHH@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 440]

global ?getViewDamping@Item@@UEBAMXZ
?getViewDamping@Item@@UEBAMXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 448]

; Item_vtable[57] is unknown

; Item_vtable[58] is unknown

; Item_vtable[59] is unknown

global ?getColor@Item@@UEBA?AVColor@mce@@PEBVCompoundTag@@AEBVItemDescriptor@@@Z
?getColor@Item@@UEBA?AVColor@mce@@PEBVCompoundTag@@AEBVItemDescriptor@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 480]

global ?hasCustomColor@Item@@UEBA_NPEBVCompoundTag@@@Z
?hasCustomColor@Item@@UEBA_NPEBVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 488]

; Item_vtable[62] is unknown

global ?clearColor@Item@@UEBAXPEAVCompoundTag@@@Z
?clearColor@Item@@UEBAXPEAVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 504]

global ?clearColor@Item@@UEBAXAEAVItemStackBase@@@Z
?clearColor@Item@@UEBAXAEAVItemStackBase@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 512]

global ?setColor@Item@@UEBAXAEAVItemStackBase@@AEBVColor@mce@@@Z
?setColor@Item@@UEBAXAEAVItemStackBase@@AEBVColor@mce@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 520]

; Item_vtable[66] is unknown

; Item_vtable[67] is unknown

global ?getActorIdentifier@Item@@UEBA?AUActorDefinitionIdentifier@@AEBVItemStack@@@Z
?getActorIdentifier@Item@@UEBA?AUActorDefinitionIdentifier@@AEBVItemStack@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 544]

global ?buildIdAux@Item@@UEBAHFPEBVCompoundTag@@@Z
?buildIdAux@Item@@UEBAHFPEBVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 552]

global ?canUseOnSimTick@Item@@UEBA_NXZ
?canUseOnSimTick@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 560]

global ?use@Item@@UEBAAEAVItemStack@@AEAV2@AEAVPlayer@@@Z
?use@Item@@UEBAAEAVItemStack@@AEAV2@AEAVPlayer@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 568]

global ?dispense@Item@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z
?dispense@Item@@UEBA_NAEAVBlockSource@@AEAVContainer@@HAEBVVec3@@E@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 576]

global ?useTimeDepleted@Item@@UEBA?AW4ItemUseMethod@@AEAVItemStack@@PEAVLevel@@PEAVPlayer@@@Z
?useTimeDepleted@Item@@UEBA?AW4ItemUseMethod@@AEAVItemStack@@PEAVLevel@@PEAVPlayer@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 584]

global ?releaseUsing@Item@@UEBAXAEAVItemStack@@PEAVPlayer@@H@Z
?releaseUsing@Item@@UEBAXAEAVItemStack@@PEAVPlayer@@H@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 592]

global ?getDestroySpeed@Item@@UEBAMAEBVItemStackBase@@AEBVBlock@@@Z
?getDestroySpeed@Item@@UEBAMAEBVItemStackBase@@AEBVBlock@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 600]

global ?hurtActor@Item@@UEBAXAEAVItemStack@@AEAVActor@@AEAVMob@@@Z
?hurtActor@Item@@UEBAXAEAVItemStack@@AEAVActor@@AEAVMob@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 608]

global ?hitActor@Item@@UEBAXAEAVItemStack@@AEAVActor@@AEAVMob@@@Z
?hitActor@Item@@UEBAXAEAVItemStack@@AEAVActor@@AEAVMob@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 616]

global ?hitBlock@Item@@UEBAXAEAVItemStack@@AEBVBlock@@AEBVBlockPos@@AEAVMob@@@Z
?hitBlock@Item@@UEBAXAEAVItemStack@@AEBVBlock@@AEBVBlockPos@@AEAVMob@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 624]

global ?mineBlock@Item@@UEBA_NAEAVItemStack@@AEBVBlock@@HHHPEAVActor@@@Z
?mineBlock@Item@@UEBA_NAEAVItemStack@@AEBVBlock@@HHHPEAVActor@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 632]

global ?buildDescriptionName@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVItemStackBase@@@Z
?buildDescriptionName@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVItemStackBase@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 640]

global ?buildDescriptionId@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVItemDescriptor@@PEBVCompoundTag@@@Z
?buildDescriptionId@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVItemDescriptor@@PEBVCompoundTag@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 648]

global ?buildEffectDescriptionName@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVItemStackBase@@@Z
?buildEffectDescriptionName@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVItemStackBase@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 656]

global ?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z
?readUserData@Item@@UEBAXAEAVItemStackBase@@AEAVIDataInput@@AEAVReadOnlyBinaryStream@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 664]

global ?writeUserData@Item@@UEBAXAEBVItemStackBase@@AEAVIDataOutput@@@Z
?writeUserData@Item@@UEBAXAEBVItemStackBase@@AEAVIDataOutput@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 672]

global ?getMaxStackSize@Item@@UEBAEAEBVItemDescriptor@@@Z
?getMaxStackSize@Item@@UEBAEAEBVItemDescriptor@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 680]

global ?inventoryTick@Item@@UEBA_NAEAVItemStack@@AEAVLevel@@AEAVActor@@H_N@Z
?inventoryTick@Item@@UEBA_NAEAVItemStack@@AEAVLevel@@AEAVActor@@H_N@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 688]

global ?refreshedInContainer@Item@@UEBAXAEBVItemStackBase@@AEAVLevel@@@Z
?refreshedInContainer@Item@@UEBAXAEBVItemStackBase@@AEAVLevel@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 696]

global ?getCooldownType@Item@@UEBAAEBVHashedString@@XZ
?getCooldownType@Item@@UEBAAEBVHashedString@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 704]

global ?getCooldownTime@Item@@UEBAHXZ
?getCooldownTime@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 712]

global ?fixupCommon@Item@@UEBAXAEAVItemStackBase@@AEAVLevel@@@Z
?fixupCommon@Item@@UEBAXAEAVItemStackBase@@AEAVLevel@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 720]

global ?fixupCommon@Item@@UEBAXAEAVItemStackBase@@@Z
?fixupCommon@Item@@UEBAXAEAVItemStackBase@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 728]

global ?getInHandUpdateType@Item@@UEBA?AW4InHandUpdateType@@AEBVPlayer@@AEBVItemStack@@1_N2@Z
?getInHandUpdateType@Item@@UEBA?AW4InHandUpdateType@@AEBVPlayer@@AEBVItemStack@@1_N2@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 736]

global ?getInHandUpdateType@Item@@UEBA?AW4InHandUpdateType@@AEBVPlayer@@AEBVItemInstance@@1_N2@Z
?getInHandUpdateType@Item@@UEBA?AW4InHandUpdateType@@AEBVPlayer@@AEBVItemInstance@@1_N2@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 744]

global ?validFishInteraction@Item@@UEBA_NH@Z
?validFishInteraction@Item@@UEBA_NH@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 752]

global ?enchantProjectile@Item@@UEBAXAEBVItemStackBase@@AEAVActor@@@Z
?enchantProjectile@Item@@UEBAXAEBVItemStackBase@@AEAVActor@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 760]

global ?getEquipLocation@Item@@UEBA?AW4ActorLocation@@XZ
?getEquipLocation@Item@@UEBA?AW4ActorLocation@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 768]

global ?getEquipSound@Item@@UEBA?AW4LevelSoundEvent@Legacy@Puv@@XZ
?getEquipSound@Item@@UEBA?AW4LevelSoundEvent@Legacy@Puv@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 776]

; Item_vtable[98] is unknown

; Item_vtable[99] is unknown

global ?hasSameRelevantUserData@Item@@UEBA_NAEBVItemStackBase@@0@Z
?hasSameRelevantUserData@Item@@UEBA_NAEBVItemStackBase@@0@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 800]

global ?initClient@Item@@UEAAXAEAVValue@Json@@AEBVSemVersion@@_NAEBVExperiments@@@Z
?initClient@Item@@UEAAXAEAVValue@Json@@AEBVSemVersion@@_NAEBVExperiments@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 808]

global ?setIconInfo@Item@@UEAAAEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z
?setIconInfo@Item@@UEAAAEAV1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@H@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 816]

global ?getIconInfo@Item@@UEBA?AUResolvedItemIconInfo@@AEBVItemStackBase@@H_N@Z
?getIconInfo@Item@@UEBA?AUResolvedItemIconInfo@@AEBVItemStackBase@@H_N@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 824]

global ?getInteractText@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVPlayer@@@Z
?getInteractText@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBVPlayer@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 832]

global ?getAnimationFrameFor@Item@@UEBAHPEAVMob@@_NPEBVItemStack@@_N@Z
?getAnimationFrameFor@Item@@UEBAHPEAVMob@@_NPEBVItemStack@@_N@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 840]

global ?isEmissive@Item@@UEBA_NH@Z
?isEmissive@Item@@UEBA_NH@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 848]

global ?getLightEmission@Item@@UEBA?AUBrightness@@H@Z
?getLightEmission@Item@@UEBA?AUBrightness@@H@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 856]

global ?getIconYOffset@Item@@UEBAHXZ
?getIconYOffset@Item@@UEBAHXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 864]

global ?canBeCharged@Item@@UEBA_NXZ
?canBeCharged@Item@@UEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 872]

global ?playSoundIncrementally@Item@@UEBAXAEBVItemStack@@AEAVMob@@@Z
?playSoundIncrementally@Item@@UEBAXAEBVItemStack@@AEAVMob@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 880]

global ?getFurnaceXPmultiplier@Item@@UEBAMAEBVItemStackBase@@@Z
?getFurnaceXPmultiplier@Item@@UEBAMAEBVItemStackBase@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 888]

global ?getAuxValuesDescription@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ
?getAuxValuesDescription@Item@@UEBA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 896]

global ?calculatePlacePos@Item@@UEBA_NAEAVItemStackBase@@AEAVActor@@AEAEAEAVBlockPos@@@Z
?calculatePlacePos@Item@@UEBA_NAEAVItemStackBase@@AEAVActor@@AEAEAEAVBlockPos@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 904]

global ?_checkUseOnPermissions@Item@@EEBA_NAEAVActor@@AEAVItemStackBase@@AEBEAEBVBlockPos@@@Z
?_checkUseOnPermissions@Item@@EEBA_NAEAVActor@@AEAVItemStackBase@@AEBEAEBVBlockPos@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 912]

global ?_calculatePlacePos@Item@@EEBA_NAEAVItemStackBase@@AEAVActor@@AEAEAEAVBlockPos@@@Z
?_calculatePlacePos@Item@@EEBA_NAEAVItemStackBase@@AEAVActor@@AEAEAEAVBlockPos@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 920]

global ?_shouldAutoCalculatePlacePos@Item@@EEBA_NXZ
?_shouldAutoCalculatePlacePos@Item@@EEBA_NXZ:
	mov rax, [rel Item_vtable]
	jmp [rax + 928]

global ?_useOn@Item@@EEBA?AVInteractionResult@@AEAVItemStack@@AEAVActor@@VBlockPos@@EAEBVVec3@@@Z
?_useOn@Item@@EEBA?AVInteractionResult@@AEAVItemStack@@AEAVActor@@VBlockPos@@EAEBVVec3@@@Z:
	mov rax, [rel Item_vtable]
	jmp [rax + 936]