#include "minecraft/src-deps/core/math/Color.hpp"

// Source: https://minecraft.wiki/w/Formatting_codes

const mce::Color mce::Color::BLACK(0x000000FF);
const mce::Color mce::Color::DARK_BLUE(0x00002AFF);
const mce::Color mce::Color::DARK_GREEN(0x002A00FF);
const mce::Color mce::Color::DARK_AQUA(0x002A2AFF);
const mce::Color mce::Color::DARK_RED(0x2A0000FF);
const mce::Color mce::Color::DARK_PURPLE(0x2A002AFF);
const mce::Color mce::Color::GOLD(0x2A2A00FF);
const mce::Color mce::Color::GRAY(0x2A2A2AFF);
const mce::Color mce::Color::DARK_GRAY(0x151515FF);
const mce::Color mce::Color::BLUE(0x15153FFF);
const mce::Color mce::Color::GREEN(0x153F15FF);
const mce::Color mce::Color::AQUA(0x153F3FFF);
const mce::Color mce::Color::RED(0x3F1515FF);
const mce::Color mce::Color::LIGHT_PURPLE(0x3F153FFF);
const mce::Color mce::Color::YELLOW(0x3F3F15FF);
const mce::Color mce::Color::WHITE(0x3F3F3FFF);
const mce::Color mce::Color::MINECOIN_GOLD(0x373501FF);
const mce::Color mce::Color::MATERIAL_QUARTZ(0x383534FF);
const mce::Color mce::Color::MATERIAL_IRON(0x333232FF);
const mce::Color mce::Color::MATERIAL_NETHERITE(0x110E0EFF);
const mce::Color mce::Color::MATERIAL_REDSTONE(0x250501FF);
const mce::Color mce::Color::MATERIAL_COPPER(0x2D1A13FF);
const mce::Color mce::Color::MATERIAL_GOLD(0x372C0BFF);
const mce::Color mce::Color::MATERIAL_EMERALD(0x04280DFF);
const mce::Color mce::Color::MATERIAL_DIAMOND(0x0B2E2AFF);
const mce::Color mce::Color::MATERIAL_LAPIS(0x08121EFF);
const mce::Color mce::Color::MATERIAL_AMETHYST(0x261731FF);

const mce::Color mce::Color::BLACK_BG(0x000000FF);
const mce::Color mce::Color::DARK_BLUE_BG(0x0000AAFF);
const mce::Color mce::Color::DARK_GREEN_BG(0x00AA00FF);
const mce::Color mce::Color::DARK_AQUA_BG(0x00AAAAFF);
const mce::Color mce::Color::DARK_RED_BG(0xAA0000FF);
const mce::Color mce::Color::DARK_PURPLE_BG(0xAA00AAFF);
const mce::Color mce::Color::GOLD_BG(0xFFAA00FF);
const mce::Color mce::Color::GRAY_BG(0xAAAAAAFF);
const mce::Color mce::Color::DARK_GRAY_BG(0x555555FF);
const mce::Color mce::Color::BLUE_BG(0x5555FFFF);
const mce::Color mce::Color::GREEN_BG(0x55FF55FF);
const mce::Color mce::Color::AQUA_BG(0x55FFFFFF);
const mce::Color mce::Color::RED_BG(0xFF5555FF);
const mce::Color mce::Color::LIGHT_PURPLE_BG(0xFF55FFFF);
const mce::Color mce::Color::YELLOW_BG(0xFFFF55FF);
const mce::Color mce::Color::WHITE_BG(0xFFFFFFFF);
const mce::Color mce::Color::MINECOIN_GOLD_BG(0xDDD605FF);
const mce::Color mce::Color::MATERIAL_QUARTZ_BG(0xE3D4D1FF);
const mce::Color mce::Color::MATERIAL_IRON_BG(0xCECACAFF);
const mce::Color mce::Color::MATERIAL_NETHERITE_BG(0x443A3BFF);
const mce::Color mce::Color::MATERIAL_REDSTONE_BG(0x971607FF);
const mce::Color mce::Color::MATERIAL_COPPER_BG(0xB4684DFF);
const mce::Color mce::Color::MATERIAL_GOLD_BG(0xDEB12DFF);
const mce::Color mce::Color::MATERIAL_EMERALD_BG(0x47A036FF);
const mce::Color mce::Color::MATERIAL_DIAMOND_BG(0x2CBAA8FF);
const mce::Color mce::Color::MATERIAL_LAPIS_BG(0x21497BFF);
const mce::Color mce::Color::MATERIAL_AMETHYST_BG(0x9A5CC6FF);
